### ISSUE TITLE
Any plans for an update?

### ISSUE THREAD

**Issue by C43H66N12O12S2** [Metalhead33/CK3-Human-Phenotype-Project#3]
Hi Leaf. Do you plan to update this mod for 1.5? This mod is great and has become an essential cornerstone for me. It'll be a shame to lose it.

**Comment by Metalhead33** [comment]
> Hi Leaf. Do you plan to update this mod for 1.5? This mod is great and has become an essential cornerstone for me. It'll be a shame to lose it.

Yes, I do plan to update it as soon as possible. Please be patient :)
