### ISSUE TITLE
Compatibility patch for Character Body Overhaul

### ISSUE THREAD

**Issue by DivannKokos** [Metalhead33/CK3-Human-Phenotype-Project#4]
[Character Body Overhaul on Loverslab](https://www.loverslab.com/files/file/16683-character-body-overhaul/)
Dunno how hard it is, but will be nice if one will exist.

**Comment by Metalhead33** [comment]
@DivannKokos : Done in the [latest release](https://www.loverslab.com/files/file/14719-ck3-human-phenotype-project/).
